---
kind: "Deployment"
apiVersion: "apps/v1"
metadata:
  name: echoserver
  labels:
    app: echoserver
spec:
  selector:
    matchLabels:
      app: echoserver
  replicas: 1
  template:
    metadata:
      labels:
        app: echoserver
    spec:
      containers:
        - name: "echoserver"
          image: "mcandre/echoserver:latest"
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "100m"
              memory: "16Mi"
            limits:
              cpu: 1
              memory: "256Mi"
          livenessProbe:
            httpGet:
              path: "/"
              port: 8080
              scheme: "HTTP"
            initialDelaySeconds: 10
          readinessProbe:
            httpGet:
              path: "/"
              port: 8080
              scheme: "HTTP"
          imagePullPolicy: "Always"
  strategy:
    type: "RollingUpdate"
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 25%
